### ISSUE TITLE
exception in ksp compilation

### ISSUE THREAD

**Issue by yigit** [google/ksp#55] opened 2020-07-01 02:24 UTC
I've hit an exception in compiler but cannot reproduce in a sample.

```
org.jetbrains.kotlin.utils.KotlinExceptionWithAttachments: Exception while analyzing expression at (339,28) in /home/yboyar/src/androidx-master-dev/frameworks/support/room/integration-tests/kotlintestapp/src/androidTest/java/androidx/room/integration/kotlintestapp/dao/BooksDao.kt
```
[full stacktrace](https://gist.github.com/yigit/aa20e141bee8264719ac22d2dbfad210)

It happens when I try to resolve the return type of a function [actual code](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:room/integration-tests/kotlintestapp/src/androidTest/java/androidx/room/integration/kotlintestapp/dao/BooksDao.kt;l=339?q=BooksDa&ss=androidx):

```
@Transaction
fun getDefaultBook() = getBook("DEFAULT_ID")

@Query("SELECT * FROM book WHERE bookId = :bookId")
fun getBook(bookId: String): Book
```

It happens when I call `funDeclaration.returnType?.resolve()`. Here, `funDeclaration` is the `KSFunctionDeclaration` of the `getDefaultBook` method.

I can help reproduce within androidx but unfortunately my efforts to isolate it didn't work :/.

**Comment by ting-yuan** [comment] 2020-12-10 02:13
Closing as it seems to be not reproducible anymore.

**Closed by ting-yuan** 2020-12-10 02:13 UTC
Labels: P3, bug
