### ISSUE TITLE
getSymbolsWithAnnotation not found

### ISSUE THREAD

**Issue by digitalheir** [google/ksp#433] opened 2021-05-18 07:17 UTC
Environment: Android Studio

Build: AI-202.7660.26.42.7351085, 202105101744, 

AI-202.7660.26.42.7351085, JRE 11.0.8+0-b944-P17168821x64 JetBrains s.r.o, OS Linux(amd64) v5.8.0-53-generic, screens 3840x2160

AS: 4.2.1; Kotlin plugin: 202-1.5.0-release-764-AS8194.7; Android Gradle Plugin: 4.2.1; Gradle: 7.0; NDK: from local.properties: (not specified), latest from SDK: (not found); LLDB: pinned revision 3.1 not found, latest from SDK: (package not found); CMake: from local.properties: (not specified), latest from SDK: 3.18.1-g262b901, from PATH: (not found)

```
e: java.lang.NoSuchMethodError: 'java.util.List com.google.devtools.ksp.processing.Resolver$DefaultImpls.getSymbolsWithAnnotation$default(com.google.devtools.ksp.processing.Resolver, java.lang.String, boolean, int, java.lang.Object)'
	at androidx.room.compiler.processing.XProcessingStep$DefaultImpls.executeInKsp(XProcessingStep.kt:72)
	at androidx.room.DatabaseProcessingStep.executeInKsp(DatabaseProcessingStep.kt:34)
	at androidx.room.RoomKspProcessor.process(RoomKspProcessor.kt:56)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:164)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:163)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:241)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:163)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:119)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:85)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:514)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:505)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:112)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:505)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:189)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:155)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:169)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:88)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1575)
	at jdk.internal.reflect.GeneratedMethodAccessor102.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by digitalheir** [comment] 2021-05-18 07:19
Why is the compilation running over a TCP connection?

**Comment by digitalheir** [comment] 2021-05-18 08:07
`alpha09` works fine

**Comment by ting-yuan** [comment] 2021-05-20 21:53
The version of Room used might not be up-to-date; `getSymbolsWithAnnotation()` was changed from returning a `List` to a `Sequence` in alpha10. Can you try to update Room?

**Comment by WhiredPlanck** [comment] 2022-09-11 06:12
> I had a similar NoSuchMethodError but complaining about Sequence, not List, when using a ksp-driven library compiled with kotlin 1.6.21 and a consumer project with kotlin 1.6.10 (and thus ksp 1.6.10-x). Upgrading project do 1.6.21 fixed the issue.

Same issue. I used Kotlin plugin v1.6.10 with Room v2.4.3 before, and have the NoSuchMethodError complaining about Sequence. I've update Kotlin plugin to v1.7.10 and the issue is fixed.

**Comment by neetopia** [comment] 2022-09-12 19:48
closed as resolved.

**Closed by neetopia** 2022-09-12 19:48 UTC
