### ISSUE TITLE
Build failing when trying to add the plugin on an Android module

### ISSUE THREAD

**Issue by gilgoldzweig** [google/ksp#314] opened 2021-02-14 07:47 UTC
I'm following the quickstart guide step by step trying to converty my annotation processor from kapt to ksp. 
I'm doing this in a new project so there are no conflicts between kapt and ksp
 
When I try to implement the plugin I receive the following exception:

`Extension of type 'CommonExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension, KspExtension]
`

I don't really know if it's important but I'm trying to implement it in an Android module. 

These are my plugins in the android module.

`plugins {
    id("com.google.devtools.ksp") version "1.4.30-1.0.0-alpha02"
    id("com.android.application")
    kotlin("android")
}`

If any information is needed I'll be happy to provide and the entire project in its current state is available here.
https://github.com/gilgoldzweig/Gencycler/tree/v3

**Comment by ting-yuan** [comment] 2021-02-17 01:26
Would you mind to try the solution in #305? Please keep this issue open even if that works.

It might have something to do with how the plugins are applied. The exception is thrown through [this line](https://github.com/google/ksp/blob/master/gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/AndroidPluginIntegration.kt#L60).

I'm still investigating but apparently get stuck. + @yigit @gavra0 any thoughts?

```
Caused by: org.gradle.api.UnknownDomainObjectException: Extension of type 'CommonExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension, KspExtension]
        at org.gradle.internal.extensibility.ExtensionsStorage.getHolderByType(ExtensionsStorage.java:88)
        at org.gradle.internal.extensibility.ExtensionsStorage.configureExtension(ExtensionsStorage.java:70)
        at org.gradle.internal.extensibility.DefaultConvention.configure(DefaultConvention.java:189)
        at org.gradle.internal.extensibility.DefaultConvention.configure(DefaultConvention.java:184)
        at com.google.devtools.ksp.gradle.AndroidPluginIntegration.decorateAndroidExtension(AndroidPluginIntegration.kt:60)
        at com.google.devtools.ksp.gradle.AndroidPluginIntegration.access$decorateAndroidExtension(AndroidPluginIntegration.kt:37)
        at com.google.devtools.ksp.gradle.AndroidPluginIntegration$applyIfAndroidProject$1.execute(AndroidPluginIntegration.kt:44)
        at com.google.devtools.ksp.gradle.AndroidPluginIntegration$applyIfAndroidProject$1.execute(AndroidPluginIntegration.kt:37)
        at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:248)
        at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:245)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:100)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:95)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        ...
```

**Comment by ting-yuan** [comment] 2021-02-17 01:34
Interestingly, this happens (in my local test project) while applying `com.android.application`:

```
An exception occurred applying plugin request [id: 'com.android.application', version: '4.2.0-beta02']
> Failed to apply plugin class 'com.android.build.gradle.api.AndroidBasePlugin'.
   > Extension of type 'CommonExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension, KspExtension]
```

**Comment by yigit** [comment] 2021-02-17 01:56
i couldn't figure out what was happening in #305 but re-doing all plugin declarations in the same place fixed it.

Specifically, we call `withPlugin` which should be waiting for the plugin to be applied.

https://docs.gradle.org/current/javadoc/org/gradle/api/plugins/PluginManager.html#withPlugin-java.lang.String-org.gradle.api.Action-
https://github.com/google/ksp/blob/master/gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/AndroidPluginIntegration.kt#L42

@gavra0 , do you think maybe this is related to watching for the base plugin instead of the sub classes? My only other guess is that maybe this happens when you apply one plugin from `plugins` block and another from `classpath`. I've not yet checked the sample

**Comment by yigit** [comment] 2021-02-17 02:18
i still don't know what is going on but i sent you a PR:

https://github.com/gilgoldzweig/Gencycler/pull/5

Again, defining all plugin versions in root fixes the issue.

@gavra0 any idea why this is happening ? Should we use something other than `withPlugin` or is this a problem gradle?

**Comment by gavra0** [comment] 2021-02-17 14:12
The issue is that AGP application/lib/dynamic-feature plugins apply the `com.android.base` plugin in their `apply()` method, which means that the callback will be invoked before the extension is created. I'll:
- upload a PR to fix this in ksp
- check AGP to apply the `com.android.base` plugin only once the "main" apply method finishes.

**Comment by gilgoldzweig** [comment] 2021-02-18 13:17
@yigit It did fix the issue and now I can compile. The only issue is that when you upgraded the Android plugin made it that I can't use Android 4.0 (I know I run an old version)

**Closed** 2021-02-19 06:56 UTC

**Comment by Gianguyen1234** [comment] 2023-10-16 09:11
Here is a way to add ksp plugin (you need to add ksp plugin in both module and project). 
Here is a video that I added ksp in android successfully: https://youtu.be/skEThDQWLig?si=gtzPnFR-FYgzyQvl
