### ISSUE TITLE
[KSP2] Generated resources are not added to KotlinCompilation inputs

### ISSUE THREAD

**Issue by ZacSweers** [google/ksp#1714] opened 2024-02-04 04:24 UTC
~Between K2 Beta1 and Beta3, this appears to have regressed and generated resources are no longer added as inputs to the Kotlin compilation.~ Sorry realizing this is actually just specific to KSP2.

Repro: https://github.com/slackhq/EitherNet/pull/72

In this project, there is a test called `EitherNetControllersTest` that exercises a service loader code path. This service loader is generated by [auto-service-ksp](https://github.com/ZacSweers/auto-service-ksp), and the specific impl loaded in this class is `SlackEndpointValidator`.

I do see the service file generated, but I do not see it marked as a source dir or visible at runtime, resulting in the current test failure on that PR.

<img width="458" alt="image" src="https://github.com/google/ksp/assets/1361086/8ba5cd1d-3d1b-43e5-87ff-f7124d114df9">

**Comment by ting-yuan** [comment] 2024-02-27 21:30
Turns out that this is caused by a bug in `KSDeclaration.packageName` which incorrectly returned an empty string for classes in libraries. In this case, the entire `com.slack.eithernet.test.ApiValidator` is treated as class name with an empty package name and therefore the `com$slack$eithernet$test$ApiValidator` in the screenshot. The package name issue is already fixed in #1724.

Verified with [2.0.0-Beta4-1.0.18-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/google/devtools/ksp/symbol-processing-aa-embeddable/2.0.0-Beta4-1.0.18-SNAPSHOT/).

**Closed by ting-yuan** 2024-02-27 21:30 UTC
Labels: bug, P1
