### ISSUE TITLE
Compatibility with Anvil

### ISSUE THREAD

**Issue by ursusursus** [google/ksp#207] opened 2020-12-22 23:15 UTC
KSP seems to interfere with Anvil (https://github.com/square/anvil) compiler plugin, causing it to not compile with rather irrelevant (to you KSP developer) error message. I filled an issue with Anvil repo and they said

> The problem is likely that they create a custom Kotlin Compile task for which Anvil registers its compiler plugin. KSP then doesn't forward the compiler plugin flags for Anvil and causes this error. (https://github.com/square/anvil/issues/171)

Here is a repro https://github.com/ursusursus/AnvilRepro2/blob/master/app/build.gradle

(I also tried the latest KSP version, same issue)

**Comment by ting-yuan** [comment] 2020-12-23 00:00
I don't think running another compiler plugin in the task created by KSP (or any other plugins) is a good idea. They should probably avoid this and only run in the main compilation task.

**Comment by vRallev** [comment] 2020-12-28 20:19
Like I mentioned in the [Anvil ticket](https://github.com/square/anvil/issues/171#issuecomment-751851362) this issue is related to KSP. It's bad if KSP breaks existing compiler plugins and also breaks APIs provided by the Kotlin compiler.

**Comment by ting-yuan** [comment] 2021-01-21 07:49
Not fixable or even workaround-able in KSP. kotlin-gradle-plugin loads compiler plugins in the configuration phase by adding them to compiler classpath. Therefore all compiler plugins are loaded in all compilation tasks, including the custom ones in KAPT and KSP. It can be worked around in ComponentRegistrar in Anvil; Subplugin options are only passed to standard compilations and Anvil has a chance to not register itself.

**Comment by vRallev** [comment] 2021-01-21 20:43
I'd like to repeat that this issue is not related to Anvil, but every compiler plugin out there. I tested it with two other compiler plugins and can reproduce the same issue. Is your plan to reach out to every plugin author and tell them to not use use [certain APIs](https://github.com/JetBrains/kotlin/blob/29b23e79f32791e456a5b4a453277f0f0b3e984d/compiler/plugin-api/src/org/jetbrains/kotlin/compiler/plugin/CliOptions.kt#L36)? 

> Not fixable or even workaround-able in KSP.

Older KSP versions didn't have this issue. One option is to revert the custom KSP task. You also have full control over the custom Gradle task that you create. As the author you control the inputs and outputs of your task.

**Comment by ting-yuan** [comment] 2021-01-22 00:08
A custom compilation task is nothing strange. kapt also does it. Anvil happens to work only because it expects to work with kapt. Tell me how you can opt out for compiler plugins that don't expect to be launched int kapt's stub generation task.

> You also have full control over the custom Gradle task that you create. As the author you control the inputs and outputs of your task.
Only if you write the plugin ground up, i.e., without using kotlin-gradle-plugin at all.

Anyway, I'm checking with upstream to see if we can change the kotlin-gradle-plugin a little bit to only add plugin classpaths in standard compilation tasks.

**Comment by vRallev** [comment] 2021-01-22 00:15
> Anyway, I'm checking with upstream to see if we can change the kotlin-gradle-plugin a little bit to only add plugin classpaths in standard compilation tasks.

That would be great. In my opinion this should happen in the Gradle plugin and not in the compiler plugin. The compiler plugin shouldn't know anything about the build tool, that's the wronger layer. 

In fact, [there's an API](https://github.com/JetBrains/kotlin/blob/master/libraries/tools/kotlin-gradle-plugin-api/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/KotlinGradleSubplugin.kt#L113-L122) that seems to built for this, but it doesn't work on a task level but on a Gradle module level, which is quite unfortunate.

**Comment by chrisjenx** [comment] 2021-01-25 19:03
Is there any known work around right now?

**Comment by ting-yuan** [comment] 2021-01-25 19:58
Some of the plugins need to run within KSP's tasks, such as AllOpen, and some don't. The final solution would be letting users (who applies the plugins in their build script) to decide which compiler plugins to enable in KSP's task. That would need some patches to be upstreamed in kotlin-gradle-plugin, as most of the relevant flags / properties are marked internal.

For now, I'm working on a patch to switch them all on or all off and hoping to land it before next release. Default will be off.

**Comment by ting-yuan** [comment] 2021-01-26 18:39
Workaround landed in #270. Note that compiler plugins are enabled by default as KSP now copies all options for them from the main compilation. Unfortunately, that also means that there is no way to tell from compiler plugins whether they are in the main compilation or customized compiler invocation now. But at least this matches KAPT's behavior and hopefully most other compiler plugins won't break. Just in case, they can also be blocked by setting `blockOtherCompilerPlugins` to true in the `ksp` extension.

**Closed by ting-yuan** 2021-01-26 18:39 UTC
