### ISSUE TITLE
Resolver.getSymbolsWithAnnotation(name, inDepth = true) ignores property getters and setters

### ISSUE THREAD

**Issue by bubenheimer** [google/ksp#1332] opened 2023-02-28 18:34 UTC
I see that `Resolver.getSymbolsWithAnnotation(name, inDepth = true)` ignores declarations inside property getters and setters. I assume this is because `visitPropertyGetter()` and `visitPropertySetter()` in `CollectAnnotatedSymbolsVisitor` do not check for local declarations, unlike `visitFunctionDeclaration()`. Merely an oversight?

https://github.com/google/ksp/blob/c145d89d1d0a591a19179a92363675e9d1660a43/common-util/src/main/kotlin/com/google/devtools/ksp/visitor/CollectAnnotatedSymbolsVisitor.kt#L57-L73

ksp 1.0.9

**Comment by neetopia** [comment] 2023-02-28 18:50
It is by design because going into bodies of property accessors does not make a lot of sense, in fact function body should already be a very limited use case therefore `inDepth` is false by default.

**Comment by bubenheimer** [comment] 2023-02-28 18:54
? I set `inDepth` to true

**Comment by neetopia** [comment] 2023-02-28 18:55
Yes, bringing up `inDepth` here is only for demonstrating body parsing is limited use case.

**Comment by bubenheimer** [comment] 2023-02-28 18:57
Wow, this behavior is really arbitrary. If I specify that I want in depth analysis, I expect as much, and not random exceptions to in-depth analysis. On top of it, this behavior is not even documented.

**Comment by bubenheimer** [comment] 2023-02-28 19:02
Annotated declarations in property accessors are as legal as they are in functions. I am not in agreement thatmy annotation processor should mislead my users and silently skip whatever annotations they might put in there.

**Comment by neetopia** [comment] 2023-02-28 19:02
You are right, we should clarify it in documents. The key different for property accessors is that they are not modeled as functions (they do not inherit `KSFunctionDeclaration`, therefore we do not intend to treat them in the same way as a function (nor should accessors be considered as function though).

**Comment by bubenheimer** [comment] 2023-03-01 08:00
This artificial limitation makes me seriously question the role of ksp, it gives me the creeps. I find it highly objectionable to limit Kotlin use cases in this covert, opinionated manner, with hardly any recourse.

**Comment by neetopia** [comment] 2023-03-02 06:52
We will support modeling local declarations for accessors in the future, an interface change will be involved.

**Closed** 2023-07-06 18:25 UTC
Labels: enhancement, P1
